name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      TAGS:
        description: 'Tags to filter tests'
        required: false
        default: ''
      ENV:
        description: 'Environment to run tests against'
        required: false
        default: 'test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'

      - name: Configure dependencies
        run: gradle dependencies

      - name: Build project
        run: gradle build -Dcucumber.env=${{ github.event.inputs.ENV || 'test' }}

      - name: Run tests
        run: |
          gradleArgs="test --info"
          if [ "${{ github.event.inputs.TAGS }}" != "" ]; then
            gradleArgs="$gradleArgs -Dcucumber.filter.tags=${{ github.event.inputs.TAGS }}"
          fi
          if [ "${{ github.event.inputs.ENV }}" != "" ]; then
            gradleArgs="$gradleArgs -Dcucumber.env=${{ github.event.inputs.ENV }}"
          fi
          gradle $gradleArgs

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: build/reports/cucumber-reports.html
